### ISSUE TITLE
Panic on promote to admin

### ISSUE THREAD

**Issue by bapril** [tridentli/trident#127]
Jan 26 19:15:01 veer systemd[6938]: Received SIGRTMIN+24 from PID 6948 (kill).
Jan 26 19:15:01 veer systemd[1]: Stopped User Manager for UID 108.
Jan 26 19:15:01 veer systemd[1]: Removed slice User Slice of trident.

^C
root@veer:/etc/postfix# tail -f /var/log/daemon.log ^C
root@veer:/etc/postfix# vi /var/log/daemon.log
Jan 26 19:08:49 veer tridentd[790]: #011/usr/lib/go-1.7/src/net/http/server.go:1579 +0xe86
Jan 26 19:08:49 veer tridentd[790]: created by net/http.(*Server).Serve
Jan 26 19:08:49 veer tridentd[790]: #011/usr/lib/go-1.7/src/net/http/server.go:2293 +0x489
Jan 26 19:09:01 veer tridentd[790]: 2018/01/26 19:09:01 http: panic serving 127.0.0.1:43410: runtime error: invalid memory address or nil pointer dereference
Jan 26 19:09:01 veer tridentd[790]: goroutine 1622 [running]:
Jan 26 19:09:01 veer tridentd[790]: net/http.(*conn).serve.func1(0x18cc9d00)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/net/http/server.go:1491 +0xa2
Jan 26 19:09:01 veer tridentd[790]: panic(0x85b87e0, 0x18b22008)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/runtime/panic.go:458 +0x40b
Jan 26 19:09:01 veer tridentd[790]: trident.li/pitchfork/ui.h_group_cmd(0x8861de0, 0x18ccb2c0)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/trident.li/pitchfork/ui/group.go:199 +0x76f
Jan 26 19:09:01 veer tridentd[790]: trident.li/pitchfork/ui.(*PfUIS).MenuPath(0x18ccb2c0, 0x18e30700, 0xf, 0x16, 0x18ccb2d0)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/trident.li/pitchfork/ui/menu.go:247 +0x9d5
Jan 26 19:09:01 veer tridentd[790]: trident.li/pitchfork/ui.(*PfUIS).UIMenu(0x18ccb2c0, 0x18b66e00, 0xb, 0xb)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/trident.li/pitchfork/ui/menu.go:264 +0x96
Jan 26 19:09:01 veer tridentd[790]: trident.li/pitchfork/ui.h_group(0x8861de0, 0x18ccb2c0)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/trident.li/pitchfork/ui/group.go:484 +0x571
Jan 26 19:09:01 veer tridentd[790]: trident.li/pitchfork/ui.(*PfUIS).MenuPath(0x18ccb2c0, 0x18cee480, 0xe, 0x1c, 0x18ccb2d0)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/trident.li/pitchfork/ui/menu.go:247 +0x9d5
Jan 26 19:09:01 veer tridentd[790]: trident.li/pitchfork/ui.(*PfUIS).UIMenu(0x18ccb2c0, 0x18c44fc0, 0xd, 0xd)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/trident.li/pitchfork/ui/menu.go:264 +0x96
Jan 26 19:09:01 veer tridentd[790]: trident.li/pitchfork/ui.(*PfRootUIS).H_root(0x18e5b780, 0x8859600, 0x18e427e0, 0x19026e00)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/trident.li/pitchfork/ui/root.go:133 +0x751
Jan 26 19:09:01 veer tridentd[790]: trident.li/pitchfork/ui.(PfRootUI).H_root-fm(0x8859600, 0x18e427e0, 0x19026e00)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/trident.li/pitchfork/cmd/server/server.go:118 +0x45
Jan 26 19:09:01 veer tridentd[790]: net/http.HandlerFunc.ServeHTTP(0x18e5b790, 0x8859600, 0x18e427e0, 0x19026e00)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/net/http/server.go:1726 +0x34
Jan 26 19:09:01 veer tridentd[790]: net/http.(*ServeMux).ServeHTTP(0x887d0a0, 0x8859600, 0x18e427e0, 0x19026e00)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/net/http/server.go:2022 +0x133
Jan 26 19:09:01 veer tridentd[790]: net/http.serverHandler.ServeHTTP(0x18b13040, 0x8859600, 0x18e427e0, 0x19026e00)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/net/http/server.go:2202 +0x136
Jan 26 19:09:01 veer tridentd[790]: net/http.(*conn).serve(0x18cc9d00, 0x8859d80, 0x18e48f60)
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/net/http/server.go:1579 +0xe86
Jan 26 19:09:01 veer tridentd[790]: created by net/http.(*Server).Serve
Jan 26 19:09:01 veer tridentd[790]: #011/usr/lib/go-1.7/src/net/http/server.go:2293 +0x489
Jan 26 19:09:24 veer tridentd[790]: 2018/01/26 19:09:24 http: panic serving 127.0.0.1:43464: runtime error: invalid memory address or nil pointer dereference
Jan 26 19:09:24 veer tridentd[790]: goroutine 1645 [running]:

**Comment by bapril** [comment]
Checks were not validating that a sysadmin is considered a user on every group.
